import {useEffect,useState} from 'react';import {api} from '../services/api';
export default function Admin(){
 const[users,setUsers]=useState([]);const[stats,setStats]=useState({});const[editing,setEditing]=useState(null);const[form,setForm]=useState({nombre:'',email:'',password:''});const[msg,setMsg]=useState('');
 const load=async()=>{try{const[u,s]=await Promise.all([api.users(),api.stats()]);setUsers(u);setStats(s)}catch(e){setMsg(e.message)}};useEffect(()=>{load()},[]);
 const save=async e=>{e.preventDefault();try{editing?await api.updateUser(editing,{...form,password:form.password||undefined}):await api.createUser(form);setForm({nombre:'',email:'',password:''});setEditing(null);setMsg('Cuenta guardada correctamente.');load()}catch(e){setMsg(e.message)}};
 const edit=u=>{setEditing(u.id_usuario);setForm({nombre:u.nombre,email:u.email,password:''})};const del=async id=>{if(confirm('¿Eliminar esta cuenta docente?')){try{await api.deleteUser(id);setMsg('Cuenta desactivada.');load()}catch(e){setMsg(e.message)}}};
 const docentes=users.filter(u=>u.rol==='docente');
 return <main className="pageSurface"><section className="pageHero adminHero"><div><span className="eyebrow">PANEL DEL ADMINISTRADOR</span><h1>Control general de la plataforma</h1><p>Supervisa docentes, materiales y retos desde un entorno claro y organizado.</p></div><button className="logoutBtn" onClick={()=>{localStorage.clear();location.reload()}}>Cerrar sesión</button></section>
 {msg&&<div className="notice">✓ {msg}</div>}
 <section className="statCards"><article><span className="statIcon green">♟</span><div><b>{stats.docentes||0}</b><small>Docentes registrados</small></div></article><article><span className="statIcon blue">▤</span><div><b>{stats.materiales||0}</b><small>Materiales publicados</small></div></article><article><span className="statIcon orange">★</span><div><b>{stats.preguntas||0}</b><small>Preguntas activas</small></div></article></section>
 <section className="adminGrid"><form className="panel adminForm" onSubmit={save}><div className="sectionHeading"><span className="sectionIcon">＋</span><div><h3>{editing?'Editar docente':'Registrar docente'}</h3><p>{editing?'Actualiza los datos de la cuenta seleccionada.':'Crea una nueva cuenta docente para la plataforma.'}</p></div></div><label>Nombre completo<input value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})} placeholder="Ej.: María López" required/></label><label>Correo electrónico<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="docente@quillo.pe" required/></label><label>{editing?'Nueva contraseña (opcional)':'Contraseña temporal'}<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder={editing?'Dejar vacío para conservar':'Mínimo recomendado: 8 caracteres'} required={!editing}/></label><div className="formActions"><button className="btnPrimary">✓ {editing?'Guardar cambios':'Registrar docente'}</button>{editing&&<button className="btnGhost" type="button" onClick={()=>{setEditing(null);setForm({nombre:'',email:'',password:''})}}>Cancelar</button>}</div></form><div className="panel teacherList"><div className="sectionHeading"><span className="sectionIcon blue">♟</span><div><h3>Gestión de docentes</h3><p>{docentes.length} cuenta{docentes.length===1?'':'s'} activa{docentes.length===1?'':'s'}.</p></div></div><div className="adminUserList">{docentes.map(u=><article key={u.id_usuario}><span className="userAvatar">{u.nombre.slice(0,1).toUpperCase()}</span><div className="userCopy"><b>{u.nombre}</b><small>{u.email}</small><span>Docente · Activo</span></div><div className="userActions"><button onClick={()=>edit(u)}>✎ Editar</button><button className="danger" onClick={()=>del(u.id_usuario)}>⌫ Eliminar</button></div></article>)}{docentes.length===0&&<div className="emptyCell">No hay cuentas docentes registradas.</div>}</div></div></section></main>
}
