import {useEffect,useMemo,useState} from 'react';import Tarjeta from '../components/Tarjeta';import {api} from '../services/api';import{demoAreas,demoLevels,demoMaterials,demoQuestions,demoSubareas}from'../data/demoData';import{downloadMaterialPdf}from'../utils/pdf';
const enrich=ms=>ms.map(m=>({...m,nivel_nombre:demoLevels.find(x=>x.id_nivel==m.id_nivel)?.nombre,area_nombre:demoAreas.find(x=>x.id_area==m.id_area)?.nombre,subarea_nombre:demoSubareas.find(x=>x.id_subarea==m.id_subarea)?.nombre}));
export default function Student(){const[catalog,setCatalog]=useState({levels:demoLevels,areas:demoAreas,subareas:demoSubareas});const[materials,setMaterials]=useState(enrich(demoMaterials));const[f,setF]=useState({q:'',nivel:'',area:'',subarea:''});const[selected,setSelected]=useState(null);const[qs,setQs]=useState([]);const[answers,setAnswers]=useState({});const[score,setScore]=useState(null);const[mode,setMode]=useState('demo');
useEffect(()=>{Promise.all([api.catalog(),api.materials()]).then(([c,m])=>{setCatalog(c);setMaterials(m);setMode('api')}).catch(()=>{})},[]);
const visible=useMemo(()=>materials.filter(m=>(!f.q||`${m.titulo} ${m.descripcion}`.toLowerCase().includes(f.q.toLowerCase()))&&(!f.nivel||m.id_nivel==f.nivel)&&(!f.area||m.id_area==f.area)&&(!f.subarea||m.id_subarea==f.subarea)),[materials,f]);
const subs=catalog.subareas.filter(s=>!f.area||s.id_area==f.area);
const open=async m=>{setSelected(m);setAnswers({});setScore(null);try{setQs(await api.challenge(m.id_material))}catch{setQs(demoQuestions[String(m.id_material)]||[])}};
const calc=()=>setScore(qs.reduce((n,q,i)=>n+(answers[i]===q.respuesta_correcta?1:0),0));
const download=()=>downloadMaterialPdf(selected);
return <main><div className="title"><div><span className="eyebrow">ÁREA DEL ESTUDIANTE</span><h2>Catálogo de aprendizaje</h2></div><span className="status">{mode==='api'?'Conectado a API/MySQL':'Modo demostración local'}</span></div><section className="filters panel"><input placeholder="Buscar tema..." value={f.q} onChange={e=>setF({...f,q:e.target.value})}/><select value={f.nivel} onChange={e=>setF({...f,nivel:e.target.value})}><option value="">Todos los niveles</option>{catalog.levels.map(x=><option key={x.id_nivel} value={x.id_nivel}>{x.nombre}</option>)}</select><select value={f.area} onChange={e=>setF({...f,area:e.target.value,subarea:''})}><option value="">Todas las áreas</option>{catalog.areas.map(x=><option key={x.id_area} value={x.id_area}>{x.nombre}</option>)}</select><select value={f.subarea} onChange={e=>setF({...f,subarea:e.target.value})}><option value="">Todas las subáreas</option>{subs.map(x=><option key={x.id_subarea} value={x.id_subarea}>{x.nombre}</option>)}</select></section><section className="cards">{visible.map(m=><Tarjeta key={m.id_material} m={m} onOpen={open}/>)}</section>{selected&&<div className="back" onClick={()=>setSelected(null)}><article className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className="pill">{selected.nivel_nombre}</span><h2>{selected.titulo}</h2><p>{selected.descripcion}</p><h3>Explicación</h3><p>{selected.contenido}</p><button onClick={download}>📄 Descargar ficha PDF</button><hr/><h3>Reto de 3 preguntas</h3>{qs.map((q,i)=><fieldset key={i}><legend>{i+1}. {q.pregunta}</legend>{q.opciones.map(op=><label className="opt" key={op}><input type="radio" name={'q'+i} onChange={()=>setAnswers({...answers,[i]:op})}/>{op}</label>)}</fieldset>)}<button className="primary" disabled={Object.keys(answers).length<qs.length} onClick={calc}>Calcular puntaje</button>{score!==null&&<div className="score">Puntaje: <b>{score}/{qs.length}</b> · {score===3?'¡Excelente!':score>=2?'¡Buen trabajo!':'Revisa la explicación y vuelve a intentar.'}</div>}</article></div>}</main>}
