import {useEffect,useMemo,useState} from 'react';
import Tarjeta from '../components/Tarjeta';import {api} from '../services/api';import{demoAreas,demoLevels,demoMaterials,demoQuestions,demoSubareas}from'../data/demoData';
const enrich=ms=>ms.map(m=>({...m,nivel_nombre:demoLevels.find(x=>x.id_nivel==m.id_nivel)?.nombre,area_nombre:demoAreas.find(x=>x.id_area==m.id_area)?.nombre,subarea_nombre:demoSubareas.find(x=>x.id_subarea==m.id_subarea)?.nombre}));
export default function Student(){
 const[catalog,setCatalog]=useState({levels:demoLevels,areas:demoAreas,subareas:demoSubareas});const[materials,setMaterials]=useState(enrich(demoMaterials));const[f,setF]=useState({q:'',nivel:'',area:'',subarea:''});const[selected,setSelected]=useState(null);const[qs,setQs]=useState([]);const[answers,setAnswers]=useState({});const[score,setScore]=useState(null);const[mode,setMode]=useState('demo');
 useEffect(()=>{Promise.all([api.catalog(),api.materials()]).then(([c,m])=>{setCatalog(c);setMaterials(m);setMode('api')}).catch(()=>{})},[]);
 const visible=useMemo(()=>materials.filter(m=>(!f.q||`${m.titulo} ${m.descripcion}`.toLowerCase().includes(f.q.toLowerCase()))&&(!f.nivel||m.id_nivel==f.nivel)&&(!f.area||m.id_area==f.area)&&(!f.subarea||m.id_subarea==f.subarea)),[materials,f]);
 const subs=catalog.subareas.filter(s=>!f.area||s.id_area==f.area);
 const open=async m=>{setSelected(m);setAnswers({});setScore(null);try{setQs(await api.challenge(m.id_material))}catch{setQs(demoQuestions[String(m.id_material)]||[])}};
 const calc=()=>setScore(qs.reduce((n,q,i)=>n+(answers[i]===q.respuesta_correcta?1:0),0));
 const download=()=>{const b=new Blob([selected.ficha],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='ficha-'+selected.id_material+'.txt';a.click();URL.revokeObjectURL(a.href)};
 const clear=()=>setF({q:'',nivel:'',area:'',subarea:''});
 return <main className="pageSurface">
  <section className="pageHero studentHero"><div><span className="eyebrow">MÓDULO DEL ESTUDIANTE</span><h1>Explora y aprende</h1><p>Selecciona un nivel, un área y un tema para fortalecer tus conocimientos paso a paso.</p></div><div className="heroStatus"><span className={mode==='api'?'onlineDot':'demoDot'}></span><div><b>{mode==='api'?'Plataforma conectada':'Modo demostración'}</b><small>{materials.length} materiales disponibles</small></div></div></section>
  <section className="studentLayout">
   <aside className="filterSidebar panel">
    <div className="sideTitle"><span>☷</span><div><h3>Filtra los materiales</h3><p>Encuentra lo que necesitas.</p></div></div>
    <label className="searchLabel">Buscar tema<input placeholder="Ej.: fracciones, cuento..." value={f.q} onChange={e=>setF({...f,q:e.target.value})}/></label>
    <div className="filterGroup"><b>Nivel</b><div className="filterPills"><button className={!f.nivel?'active':''} onClick={()=>setF({...f,nivel:''})} type="button">Todos</button>{catalog.levels.map(x=><button className={String(f.nivel)===String(x.id_nivel)?'active':''} key={x.id_nivel} onClick={()=>setF({...f,nivel:x.id_nivel})} type="button">{x.nombre}</button>)}</div></div>
    <div className="filterGroup"><b>Área</b><select value={f.area} onChange={e=>setF({...f,area:e.target.value,subarea:''})}><option value="">Todas las áreas</option>{catalog.areas.map(x=><option key={x.id_area} value={x.id_area}>{x.nombre}</option>)}</select></div>
    <div className="filterGroup"><b>Subárea</b><select value={f.subarea} onChange={e=>setF({...f,subarea:e.target.value})}><option value="">Todas las subáreas</option>{subs.map(x=><option key={x.id_subarea} value={x.id_subarea}>{x.nombre}</option>)}</select></div>
    <button type="button" className="clearFilters" onClick={clear}>↻ Limpiar filtros</button>
   </aside>
   <div className="learningMain">
    <div className="contentToolbar"><div><h2>Materiales para ti</h2><p>{visible.length} resultado{visible.length===1?'':'s'} con los filtros actuales</p></div><span className="softBadge">Aprende · Practica · Descarga</span></div>
    <section className="cards">{visible.map(m=><Tarjeta key={m.id_material} m={m} onOpen={open}/>)}</section>
    {visible.length===0&&<div className="emptyState"><span>⌕</span><h3>No encontramos materiales</h3><p>Prueba cambiando los filtros o la palabra de búsqueda.</p><button onClick={clear}>Mostrar todo</button></div>}
   </div>
   <aside className="studentAside">
    <article className="asideCard"><div className="asideIcon">★</div><h3>Tu ruta de aprendizaje</h3><p>Avanza desde Iniciación hasta Avanzado y practica en Matemática y Comunicación.</p><div className="routeStats"><div><b>{catalog.levels.length}</b><span>niveles</span></div><div><b>{catalog.subareas.length}</b><span>subáreas</span></div></div></article>
    <article className="tipCard"><span>💡</span><div><b>Consejo del día</b><p>Lee la explicación antes de resolver el reto. Puedes repetirlo cuantas veces quieras.</p></div></article>
    <article className="quilloCard"><div><span>QUILLO</span><b>Aprende y avanza</b><p>Una plataforma creada para acompañar el aprendizaje de nuestra comunidad.</p></div></article>
   </aside>
  </section>
  {selected&&<div className="back" onClick={()=>setSelected(null)}><article className="materialModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)} aria-label="Cerrar">×</button><div className="modalHead"><span className="modalSubjectIcon">{String(selected.area_nombre||'').includes('Matem')?'∑':'Aa'}</span><div><span className="levelTag">{selected.nivel_nombre}</span><div className="subjectLine">{selected.area_nombre} · {selected.subarea_nombre}</div><h2>{selected.titulo}</h2><p>{selected.descripcion}</p></div></div><div className="lessonGrid"><div className="lessonMain"><section className="lessonBlock"><div className="lessonBlockTitle"><span>▤</span><h3>Explicación</h3></div><p className="lessonText">{selected.contenido}</p><button className="downloadBtn" onClick={download}>⇩ Descargar ficha .txt</button></section><section className="lessonBlock challengeBlock"><div className="lessonBlockTitle"><span>★</span><div><h3>Reto de 3 preguntas</h3><small>Selecciona la alternativa correcta en cada pregunta.</small></div></div>{qs.length===0?<div className="noChallenge"><span>i</span><div><b>Reto pendiente de publicación</b><p>Este material fue registrado correctamente, pero aún no tiene preguntas asociadas.</p></div></div>:<>{qs.map((q,i)=><fieldset className="questionCard" key={i}><legend><span>{i+1}</span>{q.pregunta}</legend><div className="optionGrid">{q.opciones.map(op=><label className={`opt ${answers[i]===op?'selected':''}`} key={op}><input type="radio" name={'q'+i} checked={answers[i]===op} onChange={()=>setAnswers({...answers,[i]:op})}/><span>{op}</span></label>)}</div></fieldset>)}<button className="btnPrimary" disabled={Object.keys(answers).length<qs.length} onClick={calc}>✓ Calcular puntaje</button>{score!==null&&<div className="score"><span>Resultado</span><b>{score}/{qs.length}</b><p>{score===3?'¡Excelente! Dominaste este reto.':score>=2?'¡Buen trabajo! Estás muy cerca.':'Revisa la explicación y vuelve a intentarlo.'}</p></div>}</>}</section></div><aside className="lessonAside"><article><h4>Sobre este material</h4><dl><div><dt>Área</dt><dd>{selected.area_nombre}</dd></div><div><dt>Subárea</dt><dd>{selected.subarea_nombre}</dd></div><div><dt>Nivel</dt><dd>{selected.nivel_nombre}</dd></div><div><dt>Actividad</dt><dd>Explicación + reto</dd></div></dl></article><article className="lessonTip"><b>✓ Antes de responder</b><p>Lee con atención, identifica la regla o idea principal y revisa tus respuestas.</p></article></aside></div></article></div>}
 </main>
}
